/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/member'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MemberUploadRouteImport } from './routes/member.upload'
import { Route as MemberSettingsRouteImport } from './routes/member.settings'
import { Route as MemberSavingsRouteImport } from './routes/member.savings'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberLoansRouteImport } from './routes/member.loans'
import { Route as MemberApplyRouteImport } from './routes/member.apply'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSavingsRouteImport } from './routes/admin.savings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRepaymentsRouteImport } from './routes/admin.repayments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminSavingsManualRouteImport } from './routes/admin.savings.manual'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members.$id'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'

const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MemberUploadRoute = MemberUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsRoute = MemberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSavingsRoute = MemberSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLoansRoute = MemberLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => MemberRoute,
} as any)
const MemberApplyRoute = MemberApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MemberRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSavingsRoute = AdminSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepaymentsRoute = AdminRepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSavingsManualRoute = AdminSavingsManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AdminSavingsRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/savings': typeof AdminSavingsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/member/apply': typeof MemberApplyRoute
  '/member/loans': typeof MemberLoansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/savings': typeof MemberSavingsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/member/upload': typeof MemberUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/savings/manual': typeof AdminSavingsManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/savings': typeof AdminSavingsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/member/apply': typeof MemberApplyRoute
  '/member/loans': typeof MemberLoansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/savings': typeof MemberSavingsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/member/upload': typeof MemberUploadRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/savings/manual': typeof AdminSavingsManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/savings': typeof AdminSavingsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/member/apply': typeof MemberApplyRoute
  '/member/loans': typeof MemberLoansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/savings': typeof MemberSavingsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/member/upload': typeof MemberUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/savings/manual': typeof AdminSavingsManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/repayments'
    | '/admin/reports'
    | '/admin/savings'
    | '/admin/settings'
    | '/member/apply'
    | '/member/loans'
    | '/member/profile'
    | '/member/savings'
    | '/member/settings'
    | '/member/upload'
    | '/admin/'
    | '/member/'
    | '/admin/applications/$id'
    | '/admin/members/$id'
    | '/admin/savings/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/repayments'
    | '/admin/reports'
    | '/admin/savings'
    | '/admin/settings'
    | '/member/apply'
    | '/member/loans'
    | '/member/profile'
    | '/member/savings'
    | '/member/settings'
    | '/member/upload'
    | '/admin'
    | '/member'
    | '/admin/applications/$id'
    | '/admin/members/$id'
    | '/admin/savings/manual'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/loans'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/repayments'
    | '/admin/reports'
    | '/admin/savings'
    | '/admin/settings'
    | '/member/apply'
    | '/member/loans'
    | '/member/profile'
    | '/member/savings'
    | '/member/settings'
    | '/member/upload'
    | '/admin/'
    | '/member/'
    | '/admin/applications/$id'
    | '/admin/members/$id'
    | '/admin/savings/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MemberRoute: typeof MemberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/member/upload': {
      id: '/member/upload'
      path: '/upload'
      fullPath: '/member/upload'
      preLoaderRoute: typeof MemberUploadRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/settings': {
      id: '/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof MemberSettingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/savings': {
      id: '/member/savings'
      path: '/savings'
      fullPath: '/member/savings'
      preLoaderRoute: typeof MemberSavingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/loans': {
      id: '/member/loans'
      path: '/loans'
      fullPath: '/member/loans'
      preLoaderRoute: typeof MemberLoansRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/apply': {
      id: '/member/apply'
      path: '/apply'
      fullPath: '/member/apply'
      preLoaderRoute: typeof MemberApplyRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/savings': {
      id: '/admin/savings'
      path: '/savings'
      fullPath: '/admin/savings'
      preLoaderRoute: typeof AdminSavingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repayments': {
      id: '/admin/repayments'
      path: '/repayments'
      fullPath: '/admin/repayments'
      preLoaderRoute: typeof AdminRepaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/savings/manual': {
      id: '/admin/savings/manual'
      path: '/manual'
      fullPath: '/admin/savings/manual'
      preLoaderRoute: typeof AdminSavingsManualRouteImport
      parentRoute: typeof AdminSavingsRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminMembersRouteChildren {
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersIdRoute: AdminMembersIdRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminSavingsRouteChildren {
  AdminSavingsManualRoute: typeof AdminSavingsManualRoute
}

const AdminSavingsRouteChildren: AdminSavingsRouteChildren = {
  AdminSavingsManualRoute: AdminSavingsManualRoute,
}

const AdminSavingsRouteWithChildren = AdminSavingsRoute._addFileChildren(
  AdminSavingsRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLoansRoute: typeof AdminLoansRoute
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRepaymentsRoute: typeof AdminRepaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSavingsRoute: typeof AdminSavingsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminLoansRoute: AdminLoansRoute,
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRepaymentsRoute: AdminRepaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSavingsRoute: AdminSavingsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberApplyRoute: typeof MemberApplyRoute
  MemberLoansRoute: typeof MemberLoansRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberSavingsRoute: typeof MemberSavingsRoute
  MemberSettingsRoute: typeof MemberSettingsRoute
  MemberUploadRoute: typeof MemberUploadRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberApplyRoute: MemberApplyRoute,
  MemberLoansRoute: MemberLoansRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberSavingsRoute: MemberSavingsRoute,
  MemberSettingsRoute: MemberSettingsRoute,
  MemberUploadRoute: MemberUploadRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MemberRoute: MemberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
